"""
Django settings for esignature project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import ssl
from decouple import config
import django.utils.translation as original_translation
from django.utils.translation import gettext_lazy
from pathlib import Path


original_translation.ugettext_lazy = gettext_lazy


BASE_DIR = Path(__file__).resolve().parent.parent


DS_CLIENT_SECRET = config('DOCUSIGN_CLIENT_SECRET')
DOCUSIGN_CLIENT_ID = config('DOCUSIGN_CLIENT_ID')
DOCUSIGN_REDIRECT_URI = config('DOCUSIGN_REDIRECT_URI')
DOCUSIGN_AUTH_BASE_URL = config('DOCUSIGN_AUTH_BASE_URL')
DOCUSIGN_TOKEN_URL = config('DOCUSIGN_TOKEN_URL')
DOCUSIGN_ACCOUNT_ID = config('DOCUSIGN_ACCOUNT_ID')
DOCUSIGN_API_BASE_URL = config('DOCUSIGN_API_BASE_URL')
DOCUSIGN_AUTH_SERVER = config("DOCUSIGN_AUTH_SERVER", default="https://account-d.docusign.com")
DS_SCOPES = {
    "default": ["signature"],
    "Rooms": ["signature", "dtr.rooms.read"],
    "Click": ["signature", "click.manage"],
    "Admin": ["signature", "organization_read"],
    "Maestro": ["signature", "room_templates.read"],
    "WebForms": ["signature", "webforms.read"],
}
ALLOW_SILENT_AUTH = config("ALLOW_SILENT_AUTH", default=True, cast=bool)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@nz!v-e48#y!n03am#@^*kvxh-)=59m45wpnd8=ql62w8vj9_8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_docusign',
    'django_anysign',
    'rest_framework',
    'docusign',

]


# Authentication and Rest Framework settings
AUTH_USER_MODEL = 'auth.User'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
ROOT_URLCONF = 'esignature.urls'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'myapp': {  # Ensure you have a logger for your app
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
