# Generated by Django 5.1.3 on 2025-01-23 07:44

import django.utils.timezone
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenstorage',
            name='user_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokenstorage',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='tokenstorage',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
